name: Update

permissions:
  contents: write

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    strategy:
      fail-fast: false
      matrix:
        container: 
          - alt:sisyphus
          - alt:p10
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
      - name: install packages
        run: |
          apt-get update && apt-get -y install eepm git github-cli
          epm update
    
      - uses: actions/checkout@v3

      - name: fix git
        run: |
          git config --global --add safe.directory '*'

      - name: Update
        run: |
          ./update.sh
        env:
          GH_TOKEN: ${{ github.token }}
